// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'siryul.siryul', kind: "module", path: './siryul/siryul.html', attributes: []},
{name: 'siryul.siryul.AutoDetect', kind: "enumdeclaration", path: './siryul/siryul/AutoDetect.html', attributes: []},
{name: 'siryul.siryul.fromFile', kind: "functiondeclaration", path: './siryul/siryul/fromFile.html', attributes: []},
{name: 'siryul.siryul.fromString', kind: "functiondeclaration", path: './siryul/siryul/fromString.html', attributes: []},
{name: 'siryul.siryul.ISO8601', kind: "enumdeclaration", path: './siryul/siryul/ISO8601.html', attributes: []},
{name: 'siryul.siryul.ISO8601Extended', kind: "enumdeclaration", path: './siryul/siryul/ISO8601Extended.html', attributes: []},
{name: 'siryul.siryul.isSiryulizer', kind: "enummemberdeclaration", path: './siryul/siryul/isSiryulizer.html', attributes: []},
{name: 'siryul.siryul.toFile', kind: "functiondeclaration", path: './siryul/siryul/toFile.html', attributes: ["property"]},
{name: 'siryul.siryul.toFormattedString', kind: "aliasdeclaration", path: './siryul/siryul/toFormattedString.html', attributes: []},
{name: 'siryul.siryul.toString', kind: "functiondeclaration", path: './siryul/siryul/toString.html', attributes: ["auto", "property"]},
];
